spring:
  profiles:
    active: dev
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      database: class
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb
      database: class
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
