spring:
  profiles:
    active: dev
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - RewritePath=/student/(?<path>.*), /$\{path}
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**
          filters:
            - RewritePath=/teacher/(?<path>.*), /$\{path}
        - id: class-service
          uri: lb://class-service
          predicates:
            - Path=/class/**
          filters:
            - RewritePath=/class/(?<path>.*), /$\{path}


---
spring:
  profiles: dev
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
